---
# file: install.yml

- name: Create OCP config
  hosts: bastion
  roles:
  - ocp-config
  vars:
    master_count: "{{ groups['masters'] | length }}"
    worker_count: "{{ groups['workers'] | default([]) | length }}"

- name: Check and configure bootstrap node
  hosts: bootstrap
  gather_facts: no
  any_errors_fatal: true
  roles:
  - nodes-config

- name: Check and configure control-plane nodes
  hosts: masters
  gather_facts: no
  any_errors_fatal: true
  serial:
  - 1
  roles:
  - nodes-config

- name: Wait for bootstrap
  hosts: bastion[0]
  tasks:
  - name: Wait for bootstrap complete
    ansible.builtin.shell: "openshift-install wait-for bootstrap-complete --log-level {{ log_level }}"
    args:
      chdir: "{{ workdir }}"

- name: Check and configure compute nodes
  hosts: workers
  gather_facts: no
  any_errors_fatal: true
  serial:
  - 1
  roles:
  - nodes-config

- name: Install and Customize OCP
  hosts: bastion[0]
  roles:
  - ocp-install
  - ocp-customization
  vars:
    worker_count: "{{ groups['workers'] | default([]) | length }}"

- name: OCP post-install HA
  hosts: bastion[1:]
  roles:
  - ocp-ha
  vars:
    bastion_master: "{{ groups['bastion'][0] }}"
